plugins: ['github-webhook']
serverPort: 8080
livereload: false
browser: false
watcher: false
build: grunt build
serverDomains: true
webhook:
  url: '/webhook'
  secret: 'secret.pwd'
  command: git pull
  branch: deploy